In [1]:
import torch
import numpy as np

In [3]:
np_data = np.arange(6).reshape((2, 3))
np_data

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
torch_data = torch.from_numpy(np_data)
torch_data

tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)

In [7]:
torch2array = torch_data.numpy()
torch2array

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
# abs

data =[-1, -2, 1, 2]
tensor = torch.FloatTensor(data)  #32 bit

In [14]:
tensor

tensor([-1., -2.,  1.,  2.])

In [15]:
data=[[1,2],[3,4]]
tensor=torch.FloatTensor(data)

In [17]:
from torch.autograd import Variable

In [18]:
tensor = torch.FloatTensor([[1,2],[3,4]])
variable = Variable(tensor, requires_grad=True)
print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [20]:
t_out = torch.mean(tensor*tensor) #x^2
v_out = torch.mean(variable*variable)
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [21]:
v_out.backward()
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [22]:
print(variable)
print(variable.data)
print(variable.data.numpy())

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]
